version: '3.1'
services:
  springboot:
    image: prataptec22/maven-web-app-docker:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
